// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fngblryjjeixjvfaljpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuZ2JscnlqamVpeGp2ZmFsanBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NzYwMzIsImV4cCI6MjA3ODA1MjAzMn0.o5NOxUDrQ33495yED8-2EidiKfYk--7ZaC4Qfkf7iBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});